# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: messages.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'messages.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0emessages.proto\x12\x0emessageservice\"\x14\n\x12GetMessagesRequest\"\'\n\x13GetMessagesResponse\x12\x10\n\x08messages\x18\x01 \x03(\t\"3\n\x12SendMessageRequest\x12\x0f\n\x07message\x18\x01 \x01(\t\x12\x0c\n\x04uuid\x18\x02 \x01(\t\"%\n\x13SendMessageResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\"\x18\n\x16MessagesServiceRequest\"+\n\x17MessagesServiceResponse\x12\x10\n\x08response\x18\x01 \x01(\t2\xc0\x01\n\x0eLoggingService\x12V\n\x0bGetMessages\x12\".messageservice.GetMessagesRequest\x1a#.messageservice.GetMessagesResponse\x12V\n\x0bSaveMessage\x12\".messageservice.SendMessageRequest\x1a#.messageservice.SendMessageResponse2o\n\x0eMessageService\x12]\n\nGetMessage\x12&.messageservice.MessagesServiceRequest\x1a\'.messageservice.MessagesServiceResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'messages_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GETMESSAGESREQUEST']._serialized_start=34
  _globals['_GETMESSAGESREQUEST']._serialized_end=54
  _globals['_GETMESSAGESRESPONSE']._serialized_start=56
  _globals['_GETMESSAGESRESPONSE']._serialized_end=95
  _globals['_SENDMESSAGEREQUEST']._serialized_start=97
  _globals['_SENDMESSAGEREQUEST']._serialized_end=148
  _globals['_SENDMESSAGERESPONSE']._serialized_start=150
  _globals['_SENDMESSAGERESPONSE']._serialized_end=187
  _globals['_MESSAGESSERVICEREQUEST']._serialized_start=189
  _globals['_MESSAGESSERVICEREQUEST']._serialized_end=213
  _globals['_MESSAGESSERVICERESPONSE']._serialized_start=215
  _globals['_MESSAGESSERVICERESPONSE']._serialized_end=258
  _globals['_LOGGINGSERVICE']._serialized_start=261
  _globals['_LOGGINGSERVICE']._serialized_end=453
  _globals['_MESSAGESERVICE']._serialized_start=455
  _globals['_MESSAGESERVICE']._serialized_end=566
# @@protoc_insertion_point(module_scope)
